//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RimeControl.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RimeControl.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 KP_Add 的本地化字符串。
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 20190514 的本地化字符串。
        /// </summary>
        public static string app_version {
            get {
                return ResourceManager.GetString("app_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BackSpace 的本地化字符串。
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Break 的本地化字符串。
        /// </summary>
        public static string Break {
            get {
                return ResourceManager.GetString("Break", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Caps_Lock 的本地化字符串。
        /// </summary>
        public static string Capital {
            get {
                return ResourceManager.GetString("Capital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear 的本地化字符串。
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 0 的本地化字符串。
        /// </summary>
        public static string D0 {
            get {
                return ResourceManager.GetString("D0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1 的本地化字符串。
        /// </summary>
        public static string D1 {
            get {
                return ResourceManager.GetString("D1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 2 的本地化字符串。
        /// </summary>
        public static string D2 {
            get {
                return ResourceManager.GetString("D2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3 的本地化字符串。
        /// </summary>
        public static string D3 {
            get {
                return ResourceManager.GetString("D3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 4 的本地化字符串。
        /// </summary>
        public static string D4 {
            get {
                return ResourceManager.GetString("D4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 5 的本地化字符串。
        /// </summary>
        public static string D5 {
            get {
                return ResourceManager.GetString("D5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 6 的本地化字符串。
        /// </summary>
        public static string D6 {
            get {
                return ResourceManager.GetString("D6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 7 的本地化字符串。
        /// </summary>
        public static string D7 {
            get {
                return ResourceManager.GetString("D7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 8 的本地化字符串。
        /// </summary>
        public static string D8 {
            get {
                return ResourceManager.GetString("D8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 9 的本地化字符串。
        /// </summary>
        public static string D9 {
            get {
                return ResourceManager.GetString("D9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 KP_Decimal 的本地化字符串。
        /// </summary>
        public static string Decimal {
            get {
                return ResourceManager.GetString("Decimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 KP_Divide 的本地化字符串。
        /// </summary>
        public static string Divide {
            get {
                return ResourceManager.GetString("Divide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Down 的本地化字符串。
        /// </summary>
        public static string Down {
            get {
                return ResourceManager.GetString("Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 End 的本地化字符串。
        /// </summary>
        public static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Escape 的本地化字符串。
        /// </summary>
        public static string Escape {
            get {
                return ResourceManager.GetString("Escape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Execute 的本地化字符串。
        /// </summary>
        public static string Execute {
            get {
                return ResourceManager.GetString("Execute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Find 的本地化字符串。
        /// </summary>
        public static string Find {
            get {
                return ResourceManager.GetString("Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Help 的本地化字符串。
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Home 的本地化字符串。
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert 的本地化字符串。
        /// </summary>
        public static string Insert {
            get {
                return ResourceManager.GetString("Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Left 的本地化字符串。
        /// </summary>
        public static string Left {
            get {
                return ResourceManager.GetString("Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Linefeed 的本地化字符串。
        /// </summary>
        public static string Linefeed {
            get {
                return ResourceManager.GetString("Linefeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Menu 的本地化字符串。
        /// </summary>
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 KP_Multiply 的本地化字符串。
        /// </summary>
        public static string Multiply {
            get {
                return ResourceManager.GetString("Multiply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Page_Down 的本地化字符串。
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Num_Lock 的本地化字符串。
        /// </summary>
        public static string NumLock {
            get {
                return ResourceManager.GetString("NumLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 KP_0 的本地化字符串。
        /// </summary>
        public static string NumPad0 {
            get {
                return ResourceManager.GetString("NumPad0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 KP_1 的本地化字符串。
        /// </summary>
        public static string NumPad1 {
            get {
                return ResourceManager.GetString("NumPad1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 KP_2 的本地化字符串。
        /// </summary>
        public static string NumPad2 {
            get {
                return ResourceManager.GetString("NumPad2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 KP_3 的本地化字符串。
        /// </summary>
        public static string NumPad3 {
            get {
                return ResourceManager.GetString("NumPad3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 KP_4 的本地化字符串。
        /// </summary>
        public static string NumPad4 {
            get {
                return ResourceManager.GetString("NumPad4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 KP_5 的本地化字符串。
        /// </summary>
        public static string NumPad5 {
            get {
                return ResourceManager.GetString("NumPad5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 KP_6 的本地化字符串。
        /// </summary>
        public static string NumPad6 {
            get {
                return ResourceManager.GetString("NumPad6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 KP_7 的本地化字符串。
        /// </summary>
        public static string NumPad7 {
            get {
                return ResourceManager.GetString("NumPad7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 KP_8 的本地化字符串。
        /// </summary>
        public static string NumPad8 {
            get {
                return ResourceManager.GetString("NumPad8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 KP_9 的本地化字符串。
        /// </summary>
        public static string NumPad9 {
            get {
                return ResourceManager.GetString("NumPad9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ; 的本地化字符串。
        /// </summary>
        public static string Oem1 {
            get {
                return ResourceManager.GetString("Oem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 grave 的本地化字符串。
        /// </summary>
        public static string Oem3 {
            get {
                return ResourceManager.GetString("Oem3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 \ 的本地化字符串。
        /// </summary>
        public static string Oem5 {
            get {
                return ResourceManager.GetString("Oem5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 bracketright 的本地化字符串。
        /// </summary>
        public static string Oem6 {
            get {
                return ResourceManager.GetString("Oem6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 comma 的本地化字符串。
        /// </summary>
        public static string OemComma {
            get {
                return ResourceManager.GetString("OemComma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 minus 的本地化字符串。
        /// </summary>
        public static string OemMinus {
            get {
                return ResourceManager.GetString("OemMinus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 bracketleft 的本地化字符串。
        /// </summary>
        public static string OemOpenBrackets {
            get {
                return ResourceManager.GetString("OemOpenBrackets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 period 的本地化字符串。
        /// </summary>
        public static string OemPeriod {
            get {
                return ResourceManager.GetString("OemPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 plus 的本地化字符串。
        /// </summary>
        public static string OemPlus {
            get {
                return ResourceManager.GetString("OemPlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 slash 的本地化字符串。
        /// </summary>
        public static string OemQuestion {
            get {
                return ResourceManager.GetString("OemQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 apostrophe 的本地化字符串。
        /// </summary>
        public static string OemQuotes {
            get {
                return ResourceManager.GetString("OemQuotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Page_Up 的本地化字符串。
        /// </summary>
        public static string PageUp {
            get {
                return ResourceManager.GetString("PageUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pause 的本地化字符串。
        /// </summary>
        public static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Print 的本地化字符串。
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Redo 的本地化字符串。
        /// </summary>
        public static string Redo {
            get {
                return ResourceManager.GetString("Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Return 的本地化字符串。
        /// </summary>
        public static string Return {
            get {
                return ResourceManager.GetString("Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Right 的本地化字符串。
        /// </summary>
        public static string Right {
            get {
                return ResourceManager.GetString("Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Icon rime {
            get {
                object obj = ResourceManager.GetObject("rime", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Scroll_Lock 的本地化字符串。
        /// </summary>
        public static string Scroll {
            get {
                return ResourceManager.GetString("Scroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select 的本地化字符串。
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shift_Lock 的本地化字符串。
        /// </summary>
        public static string Shift_Lock {
            get {
                return ResourceManager.GetString("Shift_Lock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} (simulated) 的本地化字符串。
        /// </summary>
        public static string simulated {
            get {
                return ResourceManager.GetString("simulated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 space 的本地化字符串。
        /// </summary>
        public static string space {
            get {
                return ResourceManager.GetString("space", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 KP_Subtract 的本地化字符串。
        /// </summary>
        public static string Subtract {
            get {
                return ResourceManager.GetString("Subtract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sys_Req 的本地化字符串。
        /// </summary>
        public static string Sys_Req {
            get {
                return ResourceManager.GetString("Sys_Req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tab 的本地化字符串。
        /// </summary>
        public static string Tab {
            get {
                return ResourceManager.GetString("Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Undo 的本地化字符串。
        /// </summary>
        public static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Up 的本地化字符串。
        /// </summary>
        public static string Up {
            get {
                return ResourceManager.GetString("Up", resourceCulture);
            }
        }
    }
}
